store/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

store/orders/urls.py
from django.urls import path

from orders.views import (
    CanceledTemplateView,
    OrderCreateView,
    OrderDetailView,
    OrdersListView,
    SuccessTemplateView
)

app_name = 'orders'


urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrdersListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

store/products/urls.py
from django.urls import path

from products.views import ProductsListView, add_basket, basket_remove


app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>', ProductsListView.as_view(), name='category'),
    path('page/<int:page>', ProductsListView.as_view(), name='paginator'),
    path('basket/add/<int:product_id>/', add_basket, name='add_basket'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from orders.views import stripe_webhook_view
from products.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    # для теста вебхука stripe
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token),
]


if settings.DEBUG:
    # Добавляем toolbar
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls'))),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (
    EmailVerificationView,
    ProfileUpdateView,
    RegistrationCreateView,
    UserLoginView
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login_enter'),
    path('registration/', RegistrationCreateView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(ProfileUpdateView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification')
]

store/products/models.py
import stripe

from typing import Iterable, Optional

from django.conf import settings
from django.db import models

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    """Категории товаров."""
    name = models.CharField(
        max_length=128,
        verbose_name='Категория',
        help_text='Введите категорию'
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
        help_text='Введите описание'
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    """Товары."""
    name = models.CharField(
        max_length=256,
        verbose_name='Название товара',
        help_text='Введите название товара.'
    )
    description = models.TextField(
        verbose_name='Описание товара',
        help_text='Введите описание товара'
    )
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        verbose_name='Цена',
        help_text='Введите стоймость товара'
    )
    quantity = models.PositiveIntegerField(
        default=0,
        verbose_name='Количество',
        help_text='Введите количество')
    image = models.ImageField(
        upload_to='products_images',
        verbose_name='Изображение'
    )
    stripe_product_price_id = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        help_text='Id товара на stripe.'
    )
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self) -> str:
        return f"Продукт: {self.name} | Категория: {self.category}"

    def save(
        self, force_insert: bool = False,
        force_update: bool = False,
        using: Optional[str] = None,
        update_fields: Optional[Iterable[str]] = None
    ) -> None:
        """Изменяем метод сохранения, чтобы при создании нового объекта в бд
        он создавался и в stripe."""
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(
            force_insert=False,
            force_update=False,
            using=None,
            update_fields=None
        )

    def create_stripe_product_price(self):
        """Создание цены товара на stripe."""
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),  # так как для stripe цену нужно указывать в копейках (центах)
            currency='rub'
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    """Переопределяем менеджер для подсчёта итоговой суммы
    и общего количества товаров в корзине."""

    def total_sum(self):
        """Итоговая сумма в корзине."""
        return sum(basket.sum() for basket in self.filter())

    def total_quantity(self):
        """Итоговое количество товара в корзине."""
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        """Для отображения товаров из корзины в момент покупки в stripe."""
        line_items = []

        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }

            line_items.append(item)
        return line_items


class Basket(models.Model):
    """Корзина товаров."""
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    # Используем переопределённый менеджер для корзины
    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self) -> str:
        return f"Корзина для {self.user.username} | Продукт: {self.product.name}"

    def sum(self):
        """Цена товаров в корзине"""
        return self.product.price * self.quantity

    def de_json(self):
        """Формируем словарь для передачи в basket history.(Форма order)"""
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

    @classmethod
    def create_or_update(cls, product_id, user):
        """Создание или обновление корзины. Реализован в модели,
        чтобы не дублировать одинаковую логику,
        как для внутрянки, так и для api"""
        basket = Basket.objects.filter(user=user, product_id=product_id)

        if not basket.exists():
            obj = Basket.objects.create(
                user=user,
                product_id=product_id,
                quantity=1
            )
            # Для проверки в api, как флаг создания обьекта в корзине
            is_created = True
            return obj, is_created
        else:
            basket = basket.first()
            basket.quantity += 1
            basket.save()
            is_created = False
            return basket, is_created

store/products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.mixins import TitleMixin
from products.models import Basket, Product, ProductCategory


# Количество отображаемых товаров на странице
POSTS_IN_PAGE_FOR_PAGINATOR = 6


class IndexView(TitleMixin, TemplateView):
    """Классовое представление главной страницы."""
    template_name = 'products/index.html'
    title = '6 соток'


class ProductsListView(TitleMixin, ListView):
    """Вывод продукции магазина. Если пришёл category_id,
    то выводим только товары выбранной категории."""
    model = Product
    title = '6 соток - каталог'
    template_name = 'products/products.html'
    paginate_by = POSTS_IN_PAGE_FOR_PAGINATOR

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        # достаем из kwargs наш id категории
        category_id = self.kwargs.get('category_id')
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context


# Декоратор для проверки, что пользователь в системе
@login_required
def add_basket(request, product_id):
    """Добавление товара в корзину."""
    Basket.create_or_update(product_id, request.user)
    # Возврат на страницу, где находится пользователь
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    """Удаление товара из корзины."""
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

store/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">6 Соток </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы</a></li>

                            {% if user.is_superuser or user.is_staff %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                                    Админ-панель
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login_enter'%}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}
{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/basket.html
{% load humanize %}

{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
    </h4>
    {% for user_bas in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ user_bas.product.name }}</h5>
                <p class="card-text">{{ user_bas.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                value="{{ user_bas.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ user_bas.sum|intcomma }} руб.</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' user_bas.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
        Оформить заказ
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}

{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5" id="start-purchase-link">6 Соток</h1>
                    <p id="start-purchase-link">
                        Широкий асортимент товаров для сада.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

store/products/templates/products/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link"
                    href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% else %} # {% endif %}"
                        tabindex="-1" aria-disabled="true">
                            Предыдущая
                </a>
                </li>
                    {% for page in page_obj.paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li class="page-item">
                                <a class="page-link">
                                    {{ page }}
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endif %}
                        {% endfor %}
                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                <a class="page-link"
                                    href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% else %} # {% endif %}">
                                    Следующая
                                </a>
                            </li>
        </ul>
    </nav>
{% endif %}

store/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static humanize %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">Категории товаров</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}" class="list-group-item">
                            {{ category.name }}
                        </a>
                    {% endfor %}
                </div>

            </div>

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg"
                                alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg"
                                alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg"
                                alt="Third slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-4.jpg"
                                alt="Fourth slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                        src="{{ product.image.url }}"
                                        alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price|intcomma }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a class="btn btn-outline-success"
                                        href="{% url 'products:add_basket' product.id %}">
                                            Отправить в корзину
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                {% if is_paginated %}
                    {% include 'products/paginator.html' %}
                {% endif %}    
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store 2023</p>
        </div>
    </footer>
{% endblock %}

store/products/templates/products/request.html
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
    {% for req in request %}
        {{ req }}
    {% endfor %}
</body>
</html>